version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: db
    volumes:
      - get-cooking-data:/var/lib/postgresql/pgdata
    ports:
      - 5432:5432
    
volumes:
  get-cooking-data: {}